config/routes.rb
Rails.application.routes.draw do
  resources :videos
  root 'videos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/video.rb
class Video < ApplicationRecord
  has_attached_file :file, styles: {
      medium: { geometry: '640x480', format: 'flv' },
      mobile: { geometry: '640x480', format: 'mp4' },
      thumb: { geometry: '100x100#', format: 'jpg', time: 10 }
  }, processors: [:transcoder]

  validates_attachment_content_type :file, content_type: /\Avideo\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  before_action :set_video_type, only: :show

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all.decorate
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:name, :watermark, :file)
    end

    def set_video_type
      if request.user_agent =~ /Mobile/
        @video_type = @video.file(:mobile)
      else
        @video_type = @video.file(:medium)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
  def videojs_tag(object, type)
    video_tag type, object.file(:thumb),
              controls: true,
              class: 'video-js vjs-default-skin',
              id: 'myVideo',
              'data-watermark-text' => object.watermark
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoUploader</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="/">
              Videos
            </a>
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <%= content_for :navigation %>
            </ul>
          </div>
        </div>
      </nav>
      <%= yield %>
    </div>
  </body>
</html>

app/views/videos/_form.html.slim
= simple_form_for @video do |f|
  - if @video.errors.any?
    #error_explanation
      h2 = "#{pluralize(@video.errors.count, "error")} prohibited this video from being saved:"
      ul
        - @video.errors.full_messages.each do |message|
          li = message

  = f.input :name, placeholder: :name, as: :text

  = f.input :watermark, placeholder: :watermark, as: :text

  = f.input :file, as: :file

  = f.button :submit

app/views/videos/edit.html.slim
h1 Editing video

== render 'form'
hr
.btn-group

= content_for :navigation do
  li
    = link_to 'Show', @video

app/views/videos/index.html.slim
- @videos.each_slice(12) do |video_group|
  .row-fluid
    - video_group.each do |video|
      .col-md-2
        .thumbnail
          a href=video_path(video.object)
            = image_tag video.file.url(:thumb), alt: video.name
          .caption.row
            .col-md-6
              h4
                = video.name
              p
                = video.size
                'px
              p
                = video.length
                's
              p
                = video.file_size
                'Mb
            .col-md-6
              .pull-right
                = link_to raw('<i class="glyphicon glyphicon-pencil" aria-hidden="true"></i>'), edit_video_path(video.object), class: 'btn btn-warning'
                = link_to raw('<i class="glyphicon glyphicon-remove" aria-hidden="true"></i>'), video, data: {confirm: 'Are you sure?'}, method: :delete, class: 'btn btn-danger'
br

= link_to 'Upload new Video', new_video_path, class: 'btn btn-success'

app/views/videos/new.html.slim
h1 New video

== render 'form'

= link_to 'Back', videos_path

app/views/videos/show.html.slim
- content_for :navigation do
  li
    a.btn href=edit_video_path(@video)
      'Edit

p#notice = notice

p
  strong Name:
  = @video.name
p
  strong Watermark:
  = @video.watermark
p
  strong Length:
  = @video.file_meta['length']
p
  strong Fps:
  = @video.file_meta['fps']
p
  strong Size:
  = "#{@video.file_meta['width']} x #{@video.file_meta['height']}"
p
  strong File Size:
  = "#{@video.file_file_size} bytes"
p
  = videojs_tag(@video, @video_type)

p
  = link_to 'Original file', @video.file.url